{{- if .Values.rbac.enabled }}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.roleName }}
  namespace: {{ .Values.rbac.roleNamespace }}
rules:
  # Permissions for Tekton resources
  - apiGroups: ["tekton.dev"]
    resources: ["stepactions", "pipelines", "tasks", "pipelineruns", "taskruns", "pipelinesets", "clustertasks", "extensions"]
    verbs: ["*"]  # All actions (get, list, create, update, delete, etc.)
  - apiGroups: ["dashboard.tekton.dev"]
    resources:
      - "extensions"
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  # Permissions for Kubernetes resources related to Tekton (like pods, services, etc.)
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "deployments", "configmaps", "secrets"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.roleName }}-binding
  namespace: {{ .Values.rbac.roleNamespace }}
subjects:
  - kind: Group
    name: {{ .Values.rbac.groupName }}
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccountName }}
    namespace: {{ .Values.rbac.serviceAccountNamespace }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.roleName }}
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.clusterRoleName }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.clusterRoleBindingName }}
subjects:
  - kind: Group
    name: {{ .Values.rbac.groupName }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io

{{- end }}

