{{- if .Values.rbac.enabled }}
{{- range .Values.rbac.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .roleName }}
  namespace: {{ .roleNamespace }}
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["stepactions", "pipelines", "tasks", "pipelineruns", "taskruns", "pipelinesets", "clustertasks", "extensions"]
    verbs: ["*"]
  - apiGroups: ["dashboard.tekton.dev"]
    resources: ["extensions"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "deployments", "configmaps", "secrets"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .roleName }}-binding
  namespace: {{ .roleNamespace }}
subjects:
  - kind: Group
    name: {{ .groupName }}
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: {{ .serviceAccountName }}
    namespace: {{ .serviceAccountNamespace }}
roleRef:
  kind: Role
  name: {{ .roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- if .Values.rbac.clusterRoleName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.clusterRoleName }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
{{- end }}

{{- if .Values.rbac.clusterRoleBindingName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.clusterRoleBindingName }}
subjects:
{{- range .Values.rbac.roles }}
  - kind: Group
    name: {{ .groupName }}
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: {{ .serviceAccountName }}
    namespace: {{ .serviceAccountNamespace }}
{{- end }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}

